version: '3.9'

services:
  app:
    build: ./infra/php
    volumes:
      - ./src:/data

  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./src:/data
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./infra/nginx/error.log:/var/log/nginx/error.log
      - ./infra/nginx/access.log:/var/log/nginx/access.log

    working_dir: /data